### ISSUE TITLE
Example of passing messages prop into MessageList

### ISSUE THREAD

**Issue by abaaslx** [GetStream/stream-chat-react#1050]
Hi,

We are in the process of upgrading this package due to various issues that have come up with maintaining an old version (5.1.8).

We have two implementations of stream-chat-react components in our app.  Both use the deprecated `MessageTeam` as the UI component, in order to inject some custom functionality as props.  We need both implementations to have the same styling.

One of our use cases involves a totally custom list of messages, where some messages would render as `MessageTeam` and others would be something else.  Our existing implementation for this made use **only** of MessageTeam, overriding props as necessary, shown below.  We didn't even use `Chat` or `Channel` in this implementation, since all we needed was the `MessageTeam` UI component in order to re-use styling.  

```
const OldCustomMessage = (props) => {
  if (props.isNotStandardMessage) return <SomethingElse />
  return (
    <MessageTeam
      message={props.formattedMessage}
      getMessageActions={() => []}
      isMyMessage={() => false}
      formatDate={(date) => moment(date).format('h:mmA')}
      groupStyles={[props.position]}
    />
  )
}
```

Since MessageTeam is deprecated (and no longer works in this implementation given all of the package's context value changes), this is what I am trying to do now (unsuccessfully):

```
const NewCustomMessage = (props) => {
  if (props.isNotStandardMessage) return <SomethingElse />
  return <MessageSimple />
}

// Don't need to connect to any channels
<Chat>
  <Channel>
    <MessageList 
      messages={messageList}
      Message={NewCustomMessage}
    />
  </Channel>
 </Chat>
```

Can you please point me to an example of a custom list of messages being used in this manner or give thoughts on the above?  Could not find anything very detailed in the documentation.  I may have the formatting of the `messages` prop value wrong, but am not sure how to validate this, etc.

Would appreciate the help!

**Comment by DanC5** [comment]
Hello @abaaslx, you need to specifically connect to a channel to render any of the child components of the `Channel`, such as the `MessageList`. If you don't provide a channel object, then the `Channel` component will early return and none of its children will render. So in your above example, `MessageList` is never getting a chance to render. Also you need a valid client object on the `Chat` component for the same reasons.

Your custom Message component logic should work as long as you're explicitly providing the `isNotStandardMessage` value. So it would need to look something like this...

```
Message={(props) => <NewCustomMessage {...props} isNotStandardMessage={isNotStandardMessage} />}
```

Is all of this logic nested within existing and working `Chat` and `Channel` components? If so, you can likely removing the `Chat` and `Channel` components entirely and just render the list, otherwise you'll need to add the `client` and `channel` props, respectively.

Thanks,

**Comment by abaaslx** [comment]
> Is all of this logic nested within existing and working Chat and Channel components?
Negative - our old implementation used `MessageTeam` without nesting inside of `Chat` and `Channel`.  It was a hack (see my first snippet in OP), in order to re-use our styled-component wrapper that we used in our other implementation that _does_ use a proper `Chat` and `Channel` setup.  

What I ended up doing was

- Replacing `MessageTeam` with `MessageSimple`
- Update classnames to override styles accordingly
- Stitched together `Avatar` and some of the `MessageText` source code as an alternative to the original hack.  This way I could reproduce all the same classnames in both implementations, and use the same style overrides.

**Comment by yetieaterxb1** [comment]
Hi @abaaslx,

It sounds like your current implementation is working as you'd expect?  I am going to mark this issue as closed, if this is a mistake please reach back out and we will reopen this issue. 

We appreciate you getting in touch with us,
-Grant
