### ISSUE TITLE
Can not display entire message in ChannelPreview without being truncated

### ISSUE THREAD

**Issue by mckenziefiege** [GetStream/stream-chat-react#1052]
Is there a way to display the entire message in the ChannelPreviewMessenger component without it being truncated? Within the ChannelList component, I want to update latestMessage prop to be the entire latestMessage instead of a truncated version.

**Comment by ambaldwin** [comment]
Hi @mckenziefiege, what version of the SDK are you using? Starting with v6.3.0, the truncation in `ChannelPreviewMessenger` is handled via CSS and a max-width property so that can be overridden to be wider.

Regardless of version, you also have the option of creating your own custom preview component that will render the text in any way you'd like. [Here's an example and a good starting point](https://getstream.io/chat/docs/sdk/react/custom-code-examples/channel_list_preview/) on how to do this, and I'm updating this now with the latest version updates.

I'm going to close this issue, but let me know if you have any more questions. Thanks!
