### ISSUE TITLE
Users total_unread_count is always 0

### ISSUE THREAD

**Issue by at0misk** [GetStream/stream-chat-react#1083]
Hello, we are running into an issue trying to implement a feature that would display a users `total_unread_count` in our app. Essentially what we want to do is display the `total_unread_count` in the header of our site, and if a user has missed messages (or receives missed messages while not on their page where we currently use the `stream-chat-react` library), this number should update.

We tried to follow [these docs](https://getstream.io/chat/docs/react/unread/), but from what I can tell a user's `total_unread_count` is always 0. I tried different browsers, and I tried using ngrok and a separate computer, but that value is always 0.

Is this because once a user is "online", their messages are considered read? Please let me know if theres another way of accomplishing this, thank you in advance.

**Comment by shodgetts** [comment]
Hello, This looks like a support issue rather than a problem with the Stream-Chat-React library :) Can you please send us an email to support@getstream.io with the following information - 

app_id
user_id

We'll look forward to hearing from you soon :) This should be a relatively straightforward one to solve 

Big Steve

**Comment by at0misk** [comment]
Got this resolved btw, thank you for sending us in the right direction. Turns out we had "Read Events" toggled off in the GUI 🤦
