### ISSUE TITLE
Passing filters to searchQueryParams on Channellist component does not work as expected!

### ISSUE THREAD

**Issue by shako1988** [GetStream/stream-chat-react#1126]
Hi, 
I am trying to implement the channel search functionality on top of the channel list. **and the issue I have is that - channel search returns all channels and users - despite that I am passing a `filters` object to `<ChannelList />` component -  which filters properly the channel list on landing page, but if I pass this filters object to `searchQueryParams: {filters} `it returns just an empty result**

and this is my `filters` object:

```
{
  members: {
        $in: [userId]
    }
}
```

even if I pass the `filters` object to that property like shown bellow it just returns an empty result. 

```
<ChannelList
          filters={filters}
          sort={sort}
          showChannelSearch
          additionalChannelSearchProps={{ 
            searchForChannels: true,
            searchQueryParams: {filters: {
              $and: [ {members: { $in: someMemberID }} ] 
            }}
          }}
          List={ChannelListMessenger}
          customActiveChannel={memberChannelId}
        />
```

so can you tell me what I am doing wrong?

**Comment by shodgetts** [comment]
Hello, this looks like more of a support request :) rather than an issue with the GH repo. Can you please email support@getstream.io with your app_id? 

However, this looks like a simple case of permission checks being disabled for this app - can you check? If they are enabled and you still see this behavior please feel free to reach me and my team at the above email address :) 

BS.
