### ISSUE TITLE
No option to let ChatAutoComplete grow

### ISSUE THREAD

**Issue by HersonHN** [GetStream/stream-chat-react#1142]
I recently moved from `stream-chat-react` version 5 to 6, and everything's working fine except for one little thing.

The `<ChatAutoComplete>` components is no longer able to grow as the user types.

I can still set those properties with `useMessageInputState({ grow: true, minRows: 1, maxRows: 5 })`, but they're ignored because of these two lines:

https://github.com/GetStream/stream-chat-react/blob/576a39900bca586f6d3a660da61aceff3488e65a/src/components/AutoCompleteTextarea/Textarea.js#L447

https://github.com/GetStream/stream-chat-react/blob/576a39900bca586f6d3a660da61aceff3488e65a/src/components/AutoCompleteTextarea/Textarea.js#L683

**Comment by shodgetts** [comment]
Hello, we appreciate the report. An engineer will be able to look into this later today

**Comment by DanC5** [comment]
Hello @HersonHN, I see why the changes in 5 -> 6 around the `grow` prop are confusing. Adding this to the `useMessageInputState` hook does appear to be a dead end. In order to grow the input, you need to add the prop to the `MessageInput` component, which then gets added to the `MessageInputContext` and consumed down the tree.

`<MessageInput grow />`

This will result in the following UI update to grow the input...

![Screen Shot 2021-08-23 at 9 41 57 AM](https://user-images.githubusercontent.com/43552931/130476546-a51f224d-b4be-4b68-950b-d17d5f5c2b59.png)

Thanks for bringing this up, and I'll look more into that hook and see if any other code can be pruned. Let me know if this solves your problem so we can close out the issue, thanks.

**Comment by HersonHN** [comment]
thanks @DanC5! very helpful
