### ISSUE TITLE
StreamChat.getInstance(api_key, api_secret), get warning: "TypeError: Cannot read properties of null (reading 'sign')"

### ISSUE THREAD

**Issue by devluked** [GetStream/stream-chat-react#1160]
I'm attempting to export my channel using: 

const getChatInstance = async () => {
    const api_key = streamKey;
    const api_secret =
      "MY_API_SECRET";

    const serverClient = StreamChat.getInstance(api_key, api_secret);
    const response = await serverClient.exportChannel({
      type: channel.data.type,
      id: channel.data.id,
      messages_since: channel.data.config.created_at,
      messages_until: channel.data.updated_at,
    });

    const taskID = response.task_id;
    console.log(taskID);
  };

  getChatInstance();

But I get thrown this warning and it breaks my app: TypeError: Cannot read properties of null (reading 'sign')

This warning occurs on the line doing this:   const serverClient = StreamChat.getInstance(api_key, api_secret);

**Comment by shodgetts** [comment]
It looks like this issue is unrelated to the React SDK and is a support request. We like to reserve the GitHub issues for bug reports and feature requests etc. Can you please email support@getstream.io with your issue (please include your API key too if possible) and the integration team will help from there. 

Thanks!!

**Comment by 415brian** [comment]
@devluked, do you remember your solution here? i'm running into the same error.

**Comment by devlukedreamstage** [comment]
@415brian No sorry!
