### ISSUE TITLE
Updating more than 30 channels following connection recovery (or after `stopWatching()`/`watch()`)

### ISSUE THREAD

**Issue by kainosnoema** [GetStream/stream-chat-react#1229]
We're having a bit of trouble getting the Channel component to update properly follow connection recovery. Will try to explain the context of the situation and what we're seeing (on `stream-chat-react@6.9.0`):

- The `Channel` React component assumes that channels are always being watched and only copies channel state and updates itself on initialization of the channel and after certain events such (such as `message.new`, `connection.recovered`, etc). There doesn't seem to be a way to force a state copy, even after calling `channel.query()`. This would be fine if there were never any connection interruptions.
- Following connection recovery, the client (`stream-chat@4.20`) attempts to query up to 30 active channels using `queryChannels()` prior to dispatching the `connection.recovered` event—this order is important, since channels are queried first and then the dispatched event triggers a state copy/update in the `Channel` component immediately. This handles most cases, but [as the comments note, can only recover up to 30 channels](https://github.com/GetStream/stream-chat-js/blob/01e136f328c27175f358912f4eaa59d60cee3ba7/src/client.ts#L172-L181)—any other active channels are left with outdated state.
- We've attempted to fix this by doing as the comments suggest and disabling `recoverStateOnReconnect` and manually querying to update existing channels. The trouble with this is that as noted above, once a channel is initialized the `Channel` React component no longer attempts to copy the channel state until the next event is triggered on the client—and there doesn't appear to be a way to force this. Thus the channel has been updated behind the scenes but the component is still out of date, appearing as though the messages are not being delivered.

I feel like maybe we're just missing something very obvious here around how to properly manage channel state and get components to update after a call to `channel.query()` or `client.queryChannels()`. Assuming we're not, several ideas on how to fix this:

- Way to force the Channel component to copy channel state.
- Custom recovery callback/promise option in `stream-chat` that's waited on before the client triggers `connection.recovered`.
- **Ideally**: have the channel component listen to an event on the channel for updated state (`channel.queried`?) so it can do a throttled copy automatically. This would solve issues globally, regardless of how the state is updated.

**Comment by DanC5** [comment]
Hello @kainosnoema thanks for the details, very helpful. Have you tried pulling the `dispatch` function (which dispatches actions to the Channel reducer) from the `ChannelActionContext`? If there's a discrete moment in your app when you need to re-copy the channel state, you can programmatically dispatch this action similar to how we do in our event handler...

`dispatch({ channel, type: 'copyStateFromChannelOnEvent' })`

This is a way to hit your first bullet point locally, though if your local channel state isn't up to date then I don't think copying it would do anything.

Maybe you've tried this, but instead of calling `channel.query()` on the excess channels, have you tried calling `channel.watch()` or `channel.query({ watch: true })`. The former will get the state, but the latter two will get the state and watch for updates.

If neither of these make a difference I'll need to speak with the guys that work on the JS client. They might have run into this issue before.

**Comment by DanC5** [comment]
@kainosnoema great to hear! That's good feedback on the query listener. I'll play around for a bit and see if there's support we can add to the SDK to make this happen.

For now I'm going to close this issue, but of course let us know if further issues arise, thanks.
