### ISSUE TITLE
Not able to access resource CreateChannel on ChannelType gaming for React SDK

### ISSUE THREAD

**Issue by kshitij3027** [GetStream/stream-chat-react#1309]
Hi, i am experimenting with creating a chat based app with react using streamp api. I have been stuck on this place for some time now. I have essentially copied all the code provided in the documentation to create a channel and connect a user via the client.connectUser. I have correctly entered the api_key and user_token manually generated as in the documentation. Still the error message:

Error: StreamChat error code 17: GetOrCreateChannel failed with error: "User 'dave-matthews' with role channel_member is not allowed to access Resource CreateChannel on channel type gaming"

The code i am using in my App.js file goes something like this:

import React, { useEffect, useState } from 'react';
import { StreamChat } from 'stream-chat';
import {
  Chat,
  Channel,
  ChannelHeader,
  ChannelList,
  MessageList,
  MessageInput,
  Thread,
  Window,
} from 'stream-chat-react';
import '@stream-io/stream-chat-css/dist/css/index.css';

const filters = { type: 'messaging' };
const options = { state: true, presence: true, limit: 10 };
const sort = { last_message_at: -1 };

const client = StreamChat.getInstance('my-api-key');

const App = () => {

  const [clientReady, setClientReady] = useState(false);
  const [channel,setChannel] = useState(null)
  useEffect(() => {
    const setupClient = async () => {
      try {
        await client.connectUser(
          {
            id: 'dave-matthews',
            name: 'Dave Matthews',
          },
          'my-userToken',
        );
        const channel = await client.channel('gaming', 'gaming-demo', {
          name: 'My Gaming App',
          members: ['dave-matthews', 'trey-anastasio'],
        })
        setChannel(channel);

        setClientReady(true);
      } catch (err) {
        console.log(err);
      }
    };

    setupClient();
  }, []);

  if (!clientReady) return null;

  return (
    <Chat client={client}>
      <ChannelList filters={filters} sort={sort} options={options} />
      <Channel channel={channel}>
        <Window>
          <ChannelHeader />
          <MessageList />
          <MessageInput />
        </Window>
        <Thread />
      </Channel>
    </Chat>
  );
};

export default App;

is persisting on my system.

<img width="960" alt="error-screenshot" src="https://user-images.githubusercontent.com/54987874/145867445-0cca9279-9ff7-47f8-ac13-2139161bb162.png">

Can somebody please help me figure out what is the issue here? I have attached screenshot for reference

**Comment by kshitij3027** [comment]
A Screenshot here of the output i am getting
![Screenshot (14)](https://user-images.githubusercontent.com/54987874/145868020-df29c838-adeb-4789-a882-30142692cede.png)

**Comment by ambaldwin** [comment]
Hello, and thanks for submitting an issue to our GithHub repository. We’re glad you’re getting hands on with the product!

The Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed.

**Comment by amy-r** [comment]
hello, has this bug been fixed?

**Comment by zacheryconverse** [comment]
Hi Amy,

Thanks for reaching out - we're happy you're using our SDK. The issue here
is not a bug. It is an intended permissions issue. The permissions are
intended to prevent users that are not a member of a channel from reading
the channel. To fix this, simply ensure your filter has a minimum of:
const filter = { members: { $in: [userID] } }
Alternatively, you are able to update your permissions via the Stream
Dashboard <https://getstream.io/dashboard/>. You can find a wealth of
knowledge in our docs as well as our Knowledge Base
<https://support.getstream.io/hc/en-us> including this super helpful article
<https://support.getstream.io/hc/en-us/articles/360057461213-Filters-for-queryChannels-Chat>.
If you have any further questions, please reach out to ***@***.***,
as the issues section here is not intended for technical support.

Cheers,


*Zachery Converse* | *Software Engineer*
GetStream.io <http://getstream.io/> | Techstars NYC 2015
