### ISSUE TITLE
Custom Avatar for MessageSimple

### ISSUE THREAD

**Issue by kyriacos** [GetStream/stream-chat-react#1317]
We were using the Avatar prop to show something else in the message list (using a custom `Message` component). Seems `MessageSimple` no longer supports that. Any way i can set a custom Avatar for it?

Thanks

**Comment by yetieaterxb1** [comment]
Hi @kyriacos,

What version are you currently using? Also, are you passing the Avatar prop to Channel?

**Comment by kyriacos** [comment]
The latest version on npm.

I was not using the Avatar prop on Channel. Thank you :). 

We have a use-case that we needed different fallbacks for the ChannelHeaderPreview and the MessageList. As far as i can tell, it works now with just passing Avatar to Channel as you suggested. 

We were using `isMyMessage` so i defaulted to having a custom message component and used custom avatar component there.

There might be a regression somewhere for us but none that i can see now heh. 

It would be great if we could have the Avatar Prop passed to the MessageInput though. Easier to use in that context along with `isMyMessage` which isn't available in Channel.

Thanks for the help!

**Comment by yetieaterxb1** [comment]
Glad I could help! 

You can still access `isMyMessage` using ` const { isMyMessage } = useMessageContext();` even though this is passed to `Channel` because it will only be accessed inside the message context. 

You can then pass a separate custom `Avatar` to `ChannelList` and/or `ChannelHeader` for further customization from the defaults.

I'll go ahead and close this issue but please reach out if you have further issues with this implementation.

Best,
Grant
