### ISSUE TITLE
unintuitive behavior -- calling .disconnect() in useEffect cleanup results in errors

### ISSUE THREAD

**Issue by joshkaplan** [GetStream/stream-chat-react#1487]
### Problem
The recommended method for instantiating and cleaning up the `StreamChat` client in react produces errors in some scenarios:
1. Get a client
2. Call `connectUser` on component mount (`useEffect`) and (then pass it into the child components)
3. Call `disconnectUser` on component unmount (`useEffect` cleanup)

This is how it's done in the examples in this repo, and makes intuitive sense.

However, this currently can produce errors in some  reasonably normal scenarios:
1. If the effect fires not during a full unmount...
   * This is a common situation in react (e.g. a non-empty `deps` array.) With stream, we might want to do this to disconnect a user and connect a new user.
   * This also occurs, even with an empty `deps` array, when using "Fast Refresh", which is on by default in `create-react-app`.
2. ...AND a render occurs between the `disconnectUser` and `connectUser`. 
   * In my case, this is occurring because I need to asynchronously fetch some other values before calling `connectUser`. This is _very_ subtle, because the effect is already `async`. Simply adding one line `await someOtherFunc()` line in front of `await connectUser()` produces the errors, and it took me a while to figure out what was going on.

### Work-around
The work-around is relatively simple -- I unmount `<Chat>` components in between `disconnectUser` and `connectUser`, because I don't have a valid client at that point. However this isn't ideal because (1) it's extra logic/code and (2) It causes visual thrash for users. 

### Solution ideas
1. I think it would be more intuitive, and better for end-users, if `<Chat>` and underlying components did not throw errors when `disconnectUser()` is called, and instead showed the 'loading' screen like it does when `connectUser()` is pending. (In fact, I might even go further and also allow this _before_ `connectUser()` is called. This would allow just passing a client straight into `<Chat>`). This would mean less state management for users of this library, and less visual thrash for end-users. 
2. If this is not doable, perhaps add a line to the example code in this [repo](https://github.com/GetStream/website-react-examples) and the [docs](https://getstream.io/chat/docs/javascript/instantiating_the_client/#examples) which shows unsetting the client before calling `disconnectUser()`:
```javascript
const [chatClient, setChatClient] = useState(null); 
 
useEffect(() => { 
  const initChat = async () => { 
    const client = StreamChat.getInstance('api_key'); 
    await client.connectUser({ id: 'user_id' }, 'user_token'); 
    setChatClient(client); 
  }; 
   
  initChat(); 
   
  return () => {
    setChatClient(null); // ADD THIS LINE!
    chatClient.disconnectUser(); 
  }
}, []); 
 
if (!chatClient) return null; 
 
<Chat client={chatClient}>{/** children of Chat component*/}</Chat>; 
```

### Related
* https://github.com/GetStream/stream-chat-react/issues/1188
* https://github.com/GetStream/stream-chat-react/issues/167

**Comment by joshkaplan** [comment]
I should also mention I was using react 17 while testing this. the timing of cleanup effects apparently changed in version 17: https://reactjs.org/blog/2020/08/10/react-v17-rc.html#effect-cleanup-timing

**Comment by arnautov-anton** [comment]
Hey, @joshkaplan, thank you for pointing this out! I agree with the "connect before render" problem, I'm going to create a separate issue and I'll discuss it with the team. As for the `connectUser`/`disconnectUser` - we were actually investigating this exact issue quite recently but came to the conclusion that this is more of a documentation rather than functionality problem - partially, I'll explain; The way our JS client works we'd have to implement some sort of a "debouncing" mechanism to prevent `connectUser` method from running for a certain amount of time when there might be a consecutive call of the same method (rapid dependency array update - let's say you're switching users and you clicked twice). The way we tried to solve the problem was to await pending disconnect promise in the `connectUser` method if it existed - so if `disconnectUser` method has been called it set `pendingDisconnect`. Here's how it worked:

```tsx
useEffect(() => {
  const user = users[index];
  // 3. connectUser awaits pendingDisconnect, then runs
  chatClient.connectUser({ id: user.id }, user.token).then(() => setConnected(true));

  // 1. deps change or hot-reload (triggered by the `create-react-app`) triggers the cleaning function
  return () => {
    chatClient.disconnectUser(); // 2. disconnectUser sets pendingDisconnect promise
    setConnected(false);
  };
}, [index]);
```
This - at the first sight - solves the problem but not really. This only works if dependency array does not change "too fast". Let's assume we have three users we'd want to change between: `Anna`, `Luke` and `Jane`.
Application loads with `Anna` and then we're given the ability to change users with a button `Cycle users`. We'll press the button twice - fast:

```tsx
const users = [
  {
    id: 'anna',
    token: '<token>',
  },
  {
    id: 'luke',
    token: '<token>',
  },
  {
    id: 'jane',
    token: '<token>',
  },
];

useEffect(() => {
  // 2. new user selected (Luke - index = 1)
  const user = users[index];

  // 3. await pendingDisconnect, start connecting Luke
  chatClient.connectUser({ id: user.name }, user.key).then(() => setConnected(true));

  // 1. index dependency changed, disconnectUser gets called and sets pendingDisconnect promise
  // 4. before previous connection can finish running, dependency changed (Jane - index = 2) and disconnect has been called on pending connection resulting in crash
  return () => {
    chatClient.disconnectUser();
    setConnected(false);
  };
}, [index]);
```
Adding `pendingConnect` promise to the `disconnectUser` method to solve this problem resulted in stale visual states and duplicate connections. One of the considered solutions was "debouncing" of the `connectUser` method but since this is both BE and FE client this solution did not make sense. Current proposed solution is to document this behaviour so all of these "drawbacks" are known to our SDK users.

One of the solutions which will be added to the documentation is the disconnect promise method but done in your implementation. Here's how you'd do it:

```tsx
const disconnectReference = useRef<Promise<void>>(Promise.resolve());

useEffect(() => {
  const user = users[index];

  disconnectReference.current
    .then(() => client.connectUser({ id: user.name }, user.key))
    .then(() => {
      setConnected(true);
    });

  return () => {
    disconnectReference.current = chatClient.disconnectUser();
    setConnected(false);
  };
}, [index]);
```
This way you can use only one client instance and with UI blocking (disabling buttons during connection/disconnection) this works just fine. For rapid dependency changes I'd reccomend debouncing implementation. I'll keep in mind your solution when creating the documentation. Hope this helps, thank you for the contribution. :)

**Comment by joshkaplan** [comment]
Thanks for the detailed response! And that's a nifty solution with waiting for the prior disconnect! 

A few follow-ups:
1. I _think_ the root issue I was talking about here is slightly different (although maybe related). I was getting "can't use a channel after client.disconnect() was called." However, now I can't seem to reproduce it. I updated all my dependencies, so maybe that somehow did something 🤷 
2. For the race condition issue -- would another pattern be to just create a `new StreamClient()`on each effect fire? This would resolve the problem of multiple connects and disconnects racing each other within a client right?
3. For the race condition issue -- seems to me the **root** problem is that cleanup effects **need** to be synchronous. In other words, there needs to be some way to synchronously have client in a state where it is OK to call `connectUser()` (even if the underlying websocket connection can't be closed synchronously.) So, on `disconnectUser()`, synchronously cancel all the subscriptions to events, and then on `connectUser()` create an entirely new connection. If I'm not making sense, I can try to take a look at the client code and maybe even open a PR if that's encouraged... just link me to the relevant bits of code if you can!

**Comment by arnautov-anton** [comment]
Sure thing! I'm glad somebody's pointing this out and sharing the current findings with you is the least I can offer to (hopefully) help.

Follow-ups to your follow-ups:
1. I think the issue might be related though I'm not 100% sure. I mean it is possible that the `Chat` component tries to access channel related API calls during active disconnect resulting in such error but like I said, I'm not sure, I'd have to manually test this one.
2. I actually like this solution and I'm thinking about adding it to the documentation as it solves a good deal of currently known drawbacks. The only thing I'm afraid of are performance issues but I'd need to do some profiling first before I could reach a vedict. So if it works for you - I'd say sure!  
3. From a logical standpoint - I agree, though the client itself is large and fairly complex and contains solutions crafted for various reasons beyond my current undrestanding - If you want, I've refreshed [the branch I was working on](https://github.com/GetStream/stream-chat-js/pull/905) and you can take a look for yourself. I've given up on the problem for now but if you find an elegant solution that introduces as little breaking changes as possible then the PR is more than welcome. I'm here to answer any questions you might have and I'll try to assist you as best as I can.

Again, thank you, @joshkaplan! :)

**Comment by singh-karan-7** [comment]
This issue still exists on the latest version. Why is this closed? The hack is not a fix. Unsurprisingly, this issue only occurs in Android, not on iOS.

**Comment by arnautov-anton** [comment]
Hey, @singh-karan-7 - we developed a [new way to use our client](https://github.com/GetStream/stream-chat-react/pull/1916/files#diff-af672ddbbff02694fd008e0b44769ba3e0cfe8426745c84fe4b540520b1342edR44-R76) but we haven't released it yet because further development (testing and documentation) has been paused for now. The hook is usable though so for now - you can copy over it to your codebase and try it out. You can replace it once we officially release it, the underlying logic should not change - follow the aforementioned PR for more information.

```tsx
import { useCreateChatClient } from './hooks';

const ChatApp = ({ children }: PropsWithChildren) => {
	const chatClient = useCreateChatClient<StreamChatType>({
		'<api-key>',
		tokenOrProvider: '<user-token>',
		userData: { id: 'john', name: 'John Doe' },
	});

	if (!chatClient) return null;

	return (
		<Chat client={chatClient}>
			{children}
		</Chat>
	);
};
```
