### ISSUE TITLE
bug: (2:1) Unable to find uri in "@import https://fonts.googleapis.com/icon?family=Material+Icons"

### ISSUE THREAD

**Issue by JimmyG37** [GetStream/stream-chat-react#1533]
**Describe the bug**

Unable to find uri in "@import https://fonts.googleapis.com/icon?family=Material+Icons"

**To Reproduce**

 
yarn start command calls react-scripts start

**Expected behavior**

Compiled successfully

**Screenshots**

![Screen Shot 2022-04-19 at 2 55 24 PM](https://user-images.githubusercontent.com/68701823/164108334-7b3f6d6f-2194-4056-9882-d9ba06c50dbf.png)

**Package version**
- stream-chat-react: ^6.13.0
- stream-chat: ^3.7.0

**Desktop (please complete the following information):**

- OS: Monterey
- Browser [not browser specific]

**Additional context**

**Comment by petyosi** [comment]
Hi @JimmyG37 , we will need some more information in order to assist you further - the import in question is a valid CSS syntax, so I am not sure what's the problem. 

What are the steps to reproduce this error? What's the react/bundler setup you're using? Going through the tutorial for example seems to work as expected. If possible, please isolate the problem in a sample so that we can take a look.

Thank you in advance,

**Comment by JimmyG37** [comment]
Running yarn start is as clear as i can get to describe the steps to reproduce the error. The react/bundler setup being used is create-react-app. What seemed to work was editing the node_modules to use `@import url(https://fonts.googleapis.com/icon?family=Material+Icons)` , but there should be a better way to solve the problem. 
How would i go about isolating the problem in a sample?
Thank you for your patience

**Comment by petyosi** [comment]
You can put the simplest possible setup in a GitHub repository and link it here. We will take a look.

**Comment by JimmyG37** [comment]
Unfortunately i was not able to recreate the issue in a separate repo. Thank you for your help.
