### ISSUE TITLE
bug: thread message list autoscrolls to the bottom when a new message is received

### ISSUE THREAD

**Issue by petyosi** [GetStream/stream-chat-react#1537]
**Describe the bug**

Unlike the regular message list, the thread scrolls to the bottom when a message from another user has been received. 

**To Reproduce**

1. Open a long thread from two browsers/two users
2. User 1 - scroll up
3. User 2 - send a message
4. User 1 will get the message list scroll to the bototm.

**Expected behavior**

The message list should remain at its location for User 1.

**Comment by MartinCupela** [comment]
The actual root cause seems to be in that the scroll behavior is controlled from withing the `MessageList` component. However the `MessageList` in `Thread` is not scrollable. Instead its parent is the scrollable container. That effectively breaks automatic scrolling in `Thread`. The automatic scrolling in `Thread` happens in one of its effects and does not distinguish btw. the author of the latest message, thus scrolling indiscriminatory.
