### ISSUE TITLE
Set ChannelList data via a prop

### ISSUE THREAD

**Issue by mattlennon3** [GetStream/stream-chat-react#1539]
**Motivation**
We would like to set the `ChannelList` data via a prop. 

At the moment we are rendering something similar to the `EmptyStateIndicator`, but spread across the whole screen (replaces multiple components, including the list and chat). 
To determine if the user has any conversations, I am having to call `client.queryChannels`, check if the list is populated. 
If so, we can render `ChannelList`, which then internally does another API call to get it's data. **Meaning we are making two requests for the same data**. If not, then we just render our full page `EmptyStateIndicator` equivalent.

If I could set the `ChannelList` data via a prop, I would be able to reuse my initial API call.

I have tried to watch the value of `client.activeChannels` in a useEffect. But this only seems to update once the `ChannelList` completes its internal API call. Here is an example:
```

  const { client } = useChatContext();

  const [hasConversations, setHasConversations] = useState(false);

  useEffect(() => {
    // client.activeChannels will be empty until ChannelList loads
    // setHasConversations will be false, meaning ChannelList is not mounted and never updates client.activeChannels
    setHasConversations(!!Object.keys(client.activeChannels).length);
  }, [client.activeChannels]);

  if (!hasConversations) {
    return <NoConversations />;
  }

  return (
    <MessageContainer>
      <ChannelList
        filters={filter}
        sort={sort}
      />
      <VerticalDivider />
      <Messages />
    </MessageContainer>
  );
```

Hopefully I have just missed something obvious about the situation. Thanks for your time.

**Proposed solution**
I would like to set the `ChannelList` data via a prop.

**Comment by luisgereda** [comment]
Hi, our GH repository is reserved to report bugs in our SDK. I recommend that you take your doubts to our support channel via email to support@getsteam.io, one of our Support Engineers would be glad to help you.

To give you a quick guide, you should be pulling the data from the context instead of passing the data as a prop, it is not necessary to call the querychannels() method since the SDK does this for you already.

If you would like an extensive answer, please send us a message through our support channel

Regards,
Luis
