### ISSUE TITLE
bug: unread is 0 in channel preview when it should be > 0

### ISSUE THREAD

**Issue by apa512** [GetStream/stream-chat-react#1810]
I have a livestream channel and even if someone else posts a message the unread prop to my custom preview component remains 0.

What's odd is that `last_read` and `last_message_at` are correctly set and `last_read < last_message_at` but `unreadCount` is still 0.

Here's what I'm doing to generate the screenshot. I'm not able to post the full code but let me know if there's anything else I can provide.

```
const ChannelPreview = (props: ChannelPreviewUIComponentProps) => {
  const { channel, unread } = props;
  // unread === 0
  console.log(channel);
```

![2022-10-12-054013_2836x1131_scrot](https://user-images.githubusercontent.com/319058/195229770-f42dfcf1-627a-4859-b932-05db844e966a.png)

stream-chat-js: 7.2.0
stream-chat-react: 10.3.0

**Comment by arnautov-anton** [comment]
Channel of type `livestream` has "read events" disabled by default and that's why your `unreadCount` stays 0. You can enable these events for `livestream` channel type in the dashboard:
![image](https://user-images.githubusercontent.com/43254280/195430992-bda1475d-14fd-47bb-86f0-f891a742e8e6.png)
 or you can update it with client:
```ts
const update = await client.updateChannelType('livestream', { read_events: true });
```
Make sure to also take a look at our source code of [ChannelPreview](https://github.com/GetStream/stream-chat-react/blob/develop/src/components/ChannelPreview/ChannelPreview.tsx) to make sure you handle unread messages the best way possible. 👍
