### ISSUE TITLE
bug: css bug in css modules

### ISSUE THREAD

**Issue by CrackerJDK94** [GetStream/stream-chat-react#1833]
./node_modules/stream-chat-react/dist/css/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./node_modules/stream-chat-react/dist/css/index.css)
ParserError: Syntax Error at line: 1, column 18

when I comment //import 'stream-chat-react/dist/css/index.css';

It's work, please help me.

**Comment by petyosi** [comment]
I assume you're using the latest version of our package. The [CSS file you refer to](https://unpkg.com/browse/stream-chat-react@10.3.1/dist/css/index.css) is a valid one. You might be [facing a misconfiguration of some sort](https://stackoverflow.com/questions/63596271/webpack-with-css-loader-parsing-error-expected). 

As a troubleshooting tip, you can check one of [our working examples](https://github.com/GetStream/stream-chat-react/tree/develop/examples) or follow the tutorial [for a working setup](https://getstream.io/chat/react-chat/tutorial/) - then compare that to your current one in order to pinpoint the problem.
