### ISSUE TITLE
bug: Message options/actions aren't being shown

### ISSUE THREAD

**Issue by Chochek** [GetStream/stream-chat-react#1854]
**Describe the bug**

Message options/actions don't show on existing channels, even on new messages, but when the first message is posted to a new channel the message options/actions are displayed. As soon as I refresh they are gone and all I see is the empty "bubble" with nothing rendered inside.

**Expected behavior**

Message options/actions should always show when applicable.

**Screenshots**

![image](https://user-images.githubusercontent.com/2641549/204745239-5f8609e4-2be4-4d7d-b69d-ff6e2390a4d6.png)

![image](https://user-images.githubusercontent.com/2641549/204745252-f599e057-be46-45b6-b0a6-7834562733a7.png)

![image](https://user-images.githubusercontent.com/2641549/204745277-07a1ea05-e32f-4cf9-bc7b-5144550a297a.png)

**Package version**
- stream-chat-react: 9.5.2
- stream-chat-js: 7.2.0

**Desktop (please complete the following information):**

- OS: Mac OS Monterey 12.6
- Browser: Chrome
- Version: 108

**Additional context**

Until now we were using `stream-chat-react@5.1.7` and `stream-chat-js@3.11.0` so this was a significant upgrade :)
But from what I can tell the message options aren't being returned. We're using `MessageTeam` for the message component, that's why I didn't upgrade to v10 yet, but I tried using `MessageSimple` and even tried creating a custom message component but the same thing happens.

When I call `getMessageActions` from `useMessageContext('MessageOptions')` on an existing channel with messages I get an empty array. And when I call it on a new channel after creating the first message I get `['delete', 'edit', 'react']` which is what I set on the `MessageList` component.

**Comment by petyosi** [comment]
Hey, 

most likely, the problem you experience is a combination of some upgrade-related issue + some specific configuration on your side. In general, I would recommend that you move the MessageTeam component to your codebase and upgrade to the latest version. Keep in mind that the MessageTeam code might need some changes to function properly with the latest version. 

If the above does not solve the problem - we can assist you further. I suggest that you fork [this sandbox](https://codesandbox.io/s/stream-chat-react-tutorial-vq5ntv) so that the problem you describe is reproducible in it and contact us over email at support@getstream.io. 

Regards,
