### ISSUE TITLE
hasNextPage condition

### ISSUE THREAD

**Issue by Hanna-grepp** [GetStream/stream-chat-react#1898]
https://github.com/GetStream/stream-chat-react/blob/f2aeeee3065b10270d53d7858bf366cb33485266/src/components/ChannelList/hooks/usePaginatedChannels.ts#L58

Currently, I'm implemented the ChannelList Component with the following filters in react.

```
 // filter props
  {
      type: 'team',
      team: { $eq: id as string },
      members: { $in: [client.user?.id as string] },
    }

// renderFilterFn props
const channelFilter = (channels: Channel[]) => {
    return channels.filter((channel) => channel.type === 'team');
}
```
And I'm having problem with Paginator(LoadMorePaginator) component render condition.

The current hasNextPage condition is when `channelResponse.length` is greater than or equal to `newOptions.limit`.

In this case, when `channelResponse.length` is 30 and `newOptions.limit` is 30, the button is rendered even though there is nothing else to load.

Shouldn't the condition of the loadMore button  be 
`channelResponse.length > newOptions.limit`? Is there any other reason for `channelResponse.length >= newOptions.limit`?

**Comment by arnautov-anton** [comment]
Hey, @Hanna-grepp, current backend implementation does not provide finite channel count information so we have to "probe" for the last possible items that could be there - meaning, my finite count of channels is 6, my limit is 2, so once I load last known 2 items, the last know response count is 2 which is exactly what my limit is - if I try to load more, I get 0 items in the response which finally hides the button. Without the equal symbol in the condition you'd be able to load first two channels and then since 2 is not bigger than 2, you wouldn't be able to load the rest 4 channels. There's currently no way around this without this last "probing" request which will return 0 items. Hope this helps, closing for now.
