### ISSUE TITLE
Is there a reason to keep emoji-mart on V3 and not use the last version?

### ISSUE THREAD

**Issue by neopit** [GetStream/stream-chat-react#2005]
**Motivation**
Is there a reason to keep emoji-mart on V3 and not use the last version?

There is no clear motivation to use V5 but it appears sometimes that our users encounter the Emoji picker a little blurry.

We do not yet what is the real reason for this but it looks like the package version of this component is 2 majors version behind.
Is there a reason?

Or maybe this is not the library used by Stream? Maybe it is emojis-list?

Thx

**Proposed solution**
Use the V5.2 of emoji-mart if possible if that does not implies a lot of refactoring work or API change.

**Acceptance Criteria**
The emoji picker works as before

**Comment by arnautov-anton** [comment]
The idea is to get rid of this package from the SDK altogether and provide simple API with code snippets and documentation on how to integrate its variations into your application.

The issue is that the breaking changes the new `emoji-mart` comes with would require quite a bit of effort and time to fit into our codebase which would essentially result in breaking changes on our side as well - which is not worth it. So we decided that if we're going to be breaking stuff then we'd rather do it properly. Can't give you the exact ETA but you can track this issue: #1715
