### ISSUE TITLE
Does stream-chat-react's MessageSimple Component Indicate Edited Messages? 

### ISSUE THREAD

**Issue by mahijendra** [GetStream/stream-chat-react#2202]
` "stream-chat-react": "^10.8.8"`
 
### Description

I am currently using the `stream-chat-react` library to integrate chat functionalities into my application. My application utilizes the `MessageSimple` component for displaying messages. I have encountered a specific question regarding the handling of edited messages.

### Question

Does the `stream-chat-react` library, specifically the `MessageSimple` component, automatically provide an "Edited" label for messages that have been edited after being sent? Currently, `MessageSimple` renders the message content and the timestamp (e.g., "Today at 6:22 PM") but does not indicate if a message has been edited.

### Context

In my application, it's important for users to know when a message has been edited after its initial posting. The `MessageSimple` component handles the rendering of messages, including their timestamps, but it does not seem to display any indication of whether the message has been edited. I noticed that messages have `created_at` and `updated_at` timestamps, and I am considering using these to manually implement an "Edited" label. However, before proceeding, I wanted to confirm if such a feature already exists in the `stream-chat-react` library or if there are recommended practices for this.

### Screenshot

<img width="243" alt="Screenshot 2023-12-03 at 7 03 28 PM" src="https://github.com/GetStream/stream-chat-react/assets/39908767/764800c2-54ec-488c-87bf-cd40df2c4342">

Attached is a screenshot for reference, showing how messages are currently displayed using the `MessageSimple` component. My aim is to add an "Edited" label next to the timestamp when a message has been modified after its initial creation.

**_I want the Edited Label right after the Timestamp something like this `Today at 6:22PM (Edited).`_**

<img width="514" alt="Screenshot 2023-12-03 at 7 17 57 PM" src="https://github.com/GetStream/stream-chat-react/assets/39908767/e5bd5d21-9f4c-4384-93b7-32b251a0bb66">

## Code Usage 

```
import {
  MessageSimple,
  StreamMessage,
  useChannelStateContext,
  useMessageContext,
} from 'stream-chat-react';

export const IamCustomMessage = (): JSX.Element => {
  const { message } = useMessageContext();

  const isMessageEdited =
    message.created_at !== undefined &&
    message.updated_at !== undefined &&
    new Date(message.updated_at).getTime() >
    new Date(message.created_at).getTime();
      
return (
         <div>
               <MessageSimple />
         </div>
    );
}

```

### Additional Information

I would greatly appreciate any guidance or information regarding this feature. If it's not currently available, could you please advise on the best approach to implement this functionality manually?

**Comment by arnautov-anton** [comment]
Hey, @mahijendra! Unfortunately, our default UI component does not come with such feature but I'll keep this issue open because it makes sense to include it sometime in the future. You can implement it yourself by easily comparing `created_at` and `edited_at`, if these values don't equal, you can consider this message as edited.

**Comment by arnautov-anton** [comment]
Hey, @mahijendra  - you are correct, mistakes were made - I'm sorry, here's what I came up with that should rectify my previous statements:

```tsx
const WrappedChannel = ({ children }: PropsWithChildrenOnly) => {
  const { client } = useChatContext();

  return (
    <Channel
      doUpdateMessageRequest={(_cid, updatedMessage, options) => {
        console.log('updating', updatedMessage);
        if (!updatedMessage.edited_at) {
          updatedMessage.edited_at = new Date().toJSON();
        }
        return client.updateMessage(updatedMessage, undefined, options);
      }}
    >
      {children}
    </Channel>
  );
};
```

Here you check that if field `edited_at` does not exist on the message object, you add it and update the message through our client. You could probably extend this and update `edited_at` accordingly on subsequent message updates. This custom handler is not being triggered when the reactions are being added/removed so it shouldn't affect your expected behavior.

I see you use TypeScript so I suggest you to extend your `messageType` (`StreamChat` generic) with this extra field. :)
