### ISSUE TITLE
do not show dateSeparator if all messages were deleted for that day

### ISSUE THREAD

**Issue by plandem** [GetStream/stream-chat-react#394]
Right now we will see a date separator for a day if it ha only deleted messages. I believe it's a bad experience for user to get such spam, because it will not be clear why one day has a separator and other has not (e.g. no any message for that day at all).

From UI it should be equal (at least with fresh reload page): `no messages for particular day` == `all messages were deleted for particular day`

**Comment by jaapbakker88** [comment]
@plandem, we're currently refactoring some of our components, this issue is know to us and we're looking into fixing it.

**Comment by DanC5** [comment]
@plandem Sorry for the delay, clearing old GH issues now. We've merged an update to handle this issue, https://github.com/GetStream/stream-chat-react/pull/689. Due to how we render date insertion, I had to add an extra prop to the MessageList to support this request, `hideDeletedMessages`. When set to true, we'll no longer show MessageDeleted components and also the DateSeparator component will not display if a day only has deleted messages.
