### ISSUE TITLE
Trap and display error message in `Channel.componentDidMount()`

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-react#42]
In [`Channel.componentDidMount()`, if there is an error with `await channel.watch()`, the error message is not trapped](https://github.com/GetStream/stream-chat-react/blob/1fbd580bebf91694429da731f8db3a9ba7188572/src/components/Channel.js#L160). 

As a result, when [`Channel.render()` tries to display the error message, it shows up as just `Error: `](https://github.com/GetStream/stream-chat-react/blob/1fbd580bebf91694429da731f8db3a9ba7188572/src/components/Channel.js#L590) with no indication of what the problem was: 

![image showing the word `Error:` with no additional information](https://user-images.githubusercontent.com/140930/62485561-055f9c80-b78b-11e9-933b-38a2e59c5c07.png).

On Saturday our QA team discovered that Firefox users were unable to complete `await channel.watch()` without encountering that `Error: ` notification. This issue has been resolved, but it would be helpful to store the error so that the message can be displayed.

**Comment by vishalnarkhede** [comment]
Hey @codekiln ,

Thanks for brining this up. This is now fixed in `v0.6.22` of react sdk. 

We have added support for `LoadingErrorIndicator` component as prop to `Channel` component. It accepts error object as prop. By default [this](https://github.com/GetStream/stream-chat-react/blob/master/src/components/LoadingErrorIndicator.js) simple error message component is used.

Please reopen the issue if it doesn't the problem.
