### ISSUE TITLE
TS warning: Invalid prop `message.created_at` of type `date` supplied to `Message`, expected `string`

### ISSUE THREAD

**Issue by tomdebuyser** [GetStream/stream-chat-react#488]
I am using the example of the react chat tutorial for a channel list. There is a hiccup in the prop typings, my console is giving me a warning as shown in the image below.

I guess there is something wrong in the prop types definitiion?

<img width="634" alt="Screenshot 2020-08-17 at 14 00 19" src="https://user-images.githubusercontent.com/8437849/90394207-85a12900-e092-11ea-8f74-ea925ff8b34a.png">

gz#5362

**Comment by jaapbakker88** [comment]
@tomdebuyser thank you for reporting this, we're aware of the issue and will fix it in a future release. It should not affect your apps though.

**Comment by tomdebuyser** [comment]
I was just mentioning it indeed, nothing breaking.

Thanks for your reply!

**Comment by rgkobashi** [comment]
Hi @jaapbakker88,
Me and my team we are getting the same parsing error about `created_at` field, but also on the iOS SDK.
The problem is that on the iOS app, we cannot make use of the chat at all, since the SDK shows a banner with the text `A decoding failed: The data couldn't be read because it is missing.`

I already created a [ticket](https://getstream.zendesk.com/hc/en-us/requests/5513) but I haven't had any response yet. This has become a blocker now.

Is there is something that we can do our side?

TIA

**Comment by jaapbakker88** [comment]
@rgkobashi I can't imagine these issues related. in our web client it's proptypes complaining because we had to sync up propTypes and TS, and we can't get the propTypes to correctly match the TS. This does not impact the web client at all. It won't show in production either. 

I'll message our iOS developers to make sure they've seen this.

**Comment by rgkobashi** [comment]
Ah ok I see, we got confused then, due the similarities of the iOS client error (pasting it for reference):

```
[ERROR] ❌ keyNotFound(CodingKeys(stringValue: "created_at", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "channel", intValue: nil), DecodingKeys(stringValue: "created_by", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"created_at\", intValue: nil) (\"created_at\").", underlyingError: nil)) in parse(data:response:error:completion:)[312]
```

Will be much appreciate if your iOS devs can take a look into this 🙏

**Comment by notthatnathan** [comment]
More prop type failures w/ `stream-chat-react@2.2.2` and `stream-chat(-js)@2.1.0`.

```
Warning: Failed prop type: Invalid prop `channel` of type `Channel` supplied to `Channel`, expected instance of `Channel`.
```
```
Warning: Failed prop type: Invalid prop `channel` of type `Channel` supplied to `MessageList`, expected instance of `Channel`.
```

Nothing appears to be broken and this passes muster for the channel being passed.

```
import { Channel as StreamChannel } from 'stream-chat';
console.log('channel instanceof Channel?', channel instanceof StreamChannel);
// true
```

**Comment by banagale** [comment]
I saw this was closed, but the (benign) error still seems to be shown.

I tried installing from the newer releases not on npm yet i.e. 2.3.0-beta.0

```
"stream-chat-react": "git+ssh://git@github.com/GetStream/stream-chat-react.git#6cb9898f5fae2789b3711edee371e651a5805ba3",
```

Any suggestions on how to squelch this error?

**Comment by jaapbakker88** [comment]
@banagale the issue is not fixed. But the issue is closed. It's in our backlog right now.

**Comment by banagale** [comment]
@jaapbakker88 Thanks for the feedback. I encourage this to get some priority.

After testing the tutorial, I put a fair amount of time getting a user token endpoint set up and loaded prior to stream. I encountered errors in the console along the way, including encountering [this issue](https://dev.to/clinggit/comment/bgpa).

So when I finally got it working, I almost missed it because of the big error output in the console. I barely caught out of the corner of my eye that the chat area actually rendered.

**Comment by kainosnoema** [comment]
Also ran into this. @jaapbakker88 fwiw it's a little confusing to see this closed but not fixed. Might I recommend ensuring that Github issues status track your internal backlog? Otherwise you may have to keep answering the same questions...

**Comment by jaapbakker88** [comment]
@kainosnoema we're working on this currently, should be fixed soon.
