### ISSUE TITLE
usePinHandler crashes with custom channel type

### ISSUE THREAD

**Issue by Fnopster** [GetStream/stream-chat-react#700]
Hi,

Version 3.6.0 is crashing when used with a custom channel type. It appears that usePinHandler is crashing when it cannot find the correct permission.

### Stacktrace ###
```
Cannot read property 'admin' of undefined
    at canPin (usePinHandler.js:28)
    at usePinHandler (usePinHandler.js:73)
    at MessageActions (MessageActions.js:18)
    at MessageActions (react-hot-loader.development.js:830)
    at renderWithHooks (react-dom.development.js:14985)
```

I tried overriding it with my own pinPermissions but it's not working either.
```
         <MessageList
              Message={MessageTeam}
              pinPermissions={customPermissions}
            />
```

Debug indicates pinPermissions is not passed into the`MessageActions` component from`MessageTeam` component.

gz#9308

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/9308'>Zendesk ticket #9308</a>:<br><br>Hi

Thanks for reaching out to us.
We will check this and get back to you soon.

Cheers
Stream Team

**Comment by DanC5** [comment]
The fix for this has already been merged to master and will be released likely tomorrow, thanks!

**Comment by DanC5** [comment]
@Fnopster also please note that since you're using a custom channel type, if you want to take advantage of the pin functionality you'll need to pass in your own custom permissions object of user roles. The `pinPermissions` are passed as a prop to the MessageList component, https://github.com/GetStream/stream-chat-react/blob/master/src/components/MessageList/MessageList.js#L457
