### ISSUE TITLE
"unread" prop of Preview component is not correctly updating

### ISSUE THREAD

**Issue by tobiasbueschel** [GetStream/stream-chat-react#720]
Hey 👋 

Thanks for all your work with this component library!

I've noticed that the `unread` prop that the `Preview` component passes down is not correctly updating when a new message is received. My guess is that the following code block doesn't work correctly:

https://github.com/GetStream/stream-chat-react/blob/d936e3027a3b5df8ea2886f2d3940ae6ecc8fdf9/src/components/ChannelPreview/ChannelPreview.js#L41-L62

Steps to replicate:
- Open the console view here: https://codepen.io/tobiasbueschel/pen/KKNXyXM?editors=0011
- Notice that the count is 0
- Open another window with the Codepen app and a new user
- Send a message from this new user in one of the chats that are inactive for the first user
- Notices that the unread count of the first user is not updating correctly

Cheers

gz#9595

**Comment by tobiasbueschel** [comment]
I've had another look and it seems that the `ChannelList` component automatically marks new messages as read even though the channel is not active. This can be checked by logging out `channel.state.read` in the `Preview` component, which shows that all users have read the message despite the channel not being active.

**Comment by SeniYG** [comment]
Hi,

Can I ask if both users are watching the channel when the message is sent?

Best,

**Comment by tobiasbueschel** [comment]
> Hi,
> 
> Can I ask if both users are watching the channel when the message is sent?
> 
> Best,

Hi @SeniYG,

Thanks, both users are watching the "ChannelList" so that it gets updated in case a new message comes in. However, for both users only one channel is active.

Does that help?

**Comment by SeniYG** [comment]
Hi Tobias,

It looks like you were missing the following condition on the filters object for the ChannelList component : `members : { $in: ['broken-waterfall-5']}`. Indeed, the query channels endpoint will only return channels that the user can read, you should make sure that the query uses a filter that includes such logic. Client-side, at a minimum the filter should include `members: { $in: [userID] }.` for messaging channels, otherwise, it can create some issues with what the API returns.

Unread counts are only kept in sync for channel members.

**Comment by DanC5** [comment]
Thanks for answering this @SeniYG. @tobiasbueschel closing the issue for now, do let us know if you have questions in the future.

**Comment by govillalogic** [comment]
Hey guys @DanC5 @SeniYG 
Do you have an update on the last @tobiasbueschel question?

Your help is truly appreciated  :).
