### ISSUE TITLE
Module '"stream-chat-react"' has no exported member 'getLatestMessagePreview'.ts

### ISSUE THREAD

**Issue by tobiasbueschel** [GetStream/stream-chat-react#774]
Hi 👋 

Thanks for resolving: https://github.com/GetStream/stream-chat-react/issues/746 (@DanC5) However, I'm getting the following error when trying to import e.g. `getLatestMessagePreview`.

```
Module '"stream-chat-react"' has no exported member 'getLatestMessagePreview'.ts
```

I believe we will also need to make the respective type updates here:
https://github.com/GetStream/stream-chat-react/blob/master/types/index.d.ts

gz#10157

**Comment by DanC5** [comment]
@tobiasbueschel I see the issue here. The function can be imported no problem if you're using JS files, but this error shows up when you switch to a TS app. You are correct that it needs to be exported from index.d.ts. This will no longer be an issue when we make our full TypeScript release in a week or two, but just so you don't get stuck on this issue I'm going to make a patch release today. I'll notify you when it's live, thanks!

**Comment by tobiasbueschel** [comment]
Amazing @DanC5 thanks a lot and have a great weekend 🎉 looking forward to the TS release! Cheers

**Comment by DanC5** [comment]
Hey @tobiasbueschel, new release right here: https://github.com/GetStream/stream-chat-react/releases/tag/v4.1.3

Thanks and have a good weekend too!
