### ISSUE TITLE
Unread message count doesn't update correctly

### ISSUE THREAD

**Issue by olgen** [GetStream/stream-chat-react#796]
This implementation is missing the `message.read` event, which causes the message unread counts to be out of date:

https://github.com/GetStream/stream-chat-react/blob/master/src/components/ChannelPreview/ChannelPreview.js#L55

gz#10421

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/10421'>Zendesk ticket #10421</a>:<br><br>Hi,

Thanks for getting in touch. Could you please share your SDK version # and organization name when you have a moment?

Best,
Ryan

**Comment by ambaldwin** [comment]
@olgen Hi, can you also provide the versions of stream-chat and stream-chat-react that you're using. Thanks!

**Comment by ambaldwin** [comment]
Hi again @olgen I have looked into this issue and all seems to be working correctly. I've added the new .tsx file link for easy reference (please note we've upgraded our library to TypeSript as of v5.0.0).
https://github.com/GetStream/stream-chat-react/blob/master/src/components/ChannelPreview/ChannelPreview.tsx

The useEffect hook in the file takes the isActive boolean as a dependency and effectively updates the unread count if the channel is active so no other event listener is needed there.
Let me know if you're still seeing otherwise, otherwise I'm going to close this issue.
