### ISSUE TITLE
VirtualizedMessageList can't render null

### ISSUE THREAD

**Issue by khiemvinh97** [GetStream/stream-chat-react#812]
I have used VirtualizedMessageList for render message from the channel and remove all message had type is "null", but it not work and show  "Uncaught Error: Zero-sized element, this should not happen". 
Please help me know how to resolved it

**Comment by petyosi** [comment]
Hi, 

The virtualized message list does not support empty messages. Can you please elaborate on what you mean by:

> remove all message had type is "null", 

What are you trying to achieve?

**Comment by khiemvinh97** [comment]
I mean remove all messages had type is "deleted".  

> The virtualized message list does not support empty messages.

How I can delete a message from the list before list render

**Comment by petyosi** [comment]
My assumption is that you are using a custom message component and returning `null` for the messages with type `deleted`. If this is correct, then you should return something like 
```
<div style={{ height: '1px' }} />
```
instead. 

If this is not what you are doing, then please share your source code with us, so that we can examine it further. Thank you.

**Comment by khiemvinh97** [comment]
that exactly everything I try describes.
 It ok now, tks for you help
