### ISSUE TITLE
Can not see example on my local

### ISSUE THREAD

**Issue by congkhuong** [GetStream/stream-chat-react#840]
I follow this document to install demo on my local but not successfully

git clone git@github.com:GetStream/stream-chat-react.git
cd examples/messaging
yarn
yarn start

![image](https://user-images.githubusercontent.com/7642227/113728212-16ab3a00-9720-11eb-858b-8b52cc9c305d.png)

**Comment by gunratnamore911** [comment]
have you installed dependencies ?

**Comment by ath92** [comment]
Hi @congkhuong, I'm not able to reproduce this error locally.

If you haven't, could you try to run the following steps in order to see if it resolves your issues?

 - run `yarn` inside the project root folder (i.e. the folder into which you cloned `stream-chat-react`)
 - Do the same inside the messaging example folder (I believe this is one of the steps you outlined in your question)
 - Make sure you have provide the needed environment variables - you can go through the example's `App.js` to see which variables are actually used. Here's a link that could give you some additional information: https://www.freecodecamp.org/news/heres-how-you-can-actually-use-node-environment-variables-8fdf98f53a0a/
 - Now when you run `yarn start` in the example folder, things should work as expected.

Let me know if you have any questions about these steps.
