### ISSUE TITLE
Cannot load stream-chat-react/dist/css/index.css in Gatby

### ISSUE THREAD

**Issue by cabutler10** [GetStream/stream-chat-react#845]
**Issue:** 
I am unable to use the css files in stream-chat-react when using Gatsby

**Error:**
```
ERROR in ./node_modules/stream-chat-react/dist/css/index.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
URIError: URI malformed
...
```

Please see the demo repo here to reproduce this error (very basic Gatsby website with a stream-chat-react demo);
[test-stream-chat-react](https://github.com/cabutler10/test-stream-chat-react)

Note in test-stream-chat-react/src/App.js line 18, please add an API key. 

When I remove the line 
`import "stream-chat-react/dist/css/index.css";`
the app will run, but it gives the above error when the line is included. Is there some workaround when using Gatsby that I missed in the documentation somewhere? Any help pointing me to the correct use of the css would be greatly appreciated, thanks!

**Comment by ath92** [comment]
Hi @cabutler10,

Thanks for reaching out about this. It seems that this error was thrown because of an old piece of css that hasn't been changed in the last 2 years. It turns out that we were no longer using this particular bit of styling anywhere in our library, so I decided to just remove it (see #846). If that PR gets merged in, we'll create a patch release which will resolve your issue.

In the meantime, it should be safe to remove the offending bit of css from the file that sits in your `node_modules/stream-chat-react/dist/css/index.css` (anything related to `str-chat__message-reactions-box`). This is purely meant as a workaround; any subsequent installations of `stream-chat-react` at the currently released version will still include the css, and will override your deletions, but it will at least allow you to continue development while you wait for the patch to be released.

**Comment by cabutler10** [comment]
Thank you, this solves the issue!

**Comment by starucan-kyna** [comment]
Failed to parse source map from 'C:\Users\Jay Ace\Desktop\medical-pager\client\node_modules\stream-chat-react\dist\css\index.css.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\Jay Ace\Desktop\medical-pager\client\node_modules\stream-chat-react\dist\css\index.css.map'

this is my error
![image](https://user-images.githubusercontent.com/102565261/170802223-17b1f5bd-e3eb-4ce4-99b3-b90dd9b27a06.png)
