### ISSUE TITLE
Cannot pin message

### ISSUE THREAD

**Issue by thedang** [GetStream/stream-chat-react#848]
I had just test on your demo, feature pin message.

https://getstream.io/chat/demos/team/

First time, i pinned a message success, but when i switched another channel or reload page, then pin message lost.

gz#10975

**Comment by DanC5** [comment]
@thedang The pinned message is not persistent because the demo apps were built prior to our pinned message api being built. The demo is currently just a UI representation, but we are currently in the process of converting the demos to TypeScript and in this process will swap out the UI mock for the actual pin logic. Closing this issue because the team demo app rebuild is virtually complete and will likely be deployed next week with the updated pin handling.
