### ISSUE TITLE
Safari 14.0.3 consistently showing Network Error on load of chat client

### ISSUE THREAD

**Issue by jberhang** [GetStream/stream-chat-react#862]
This is easily reproducible using the chat demo: https://getstream.io/chat/demos/gaming/. Refreshing the demo page usually shows the issue 50% of the time.

<img width="288" alt="Screen Shot 2021-04-20 at 9 35 22 AM" src="https://user-images.githubusercontent.com/3286252/115404954-ca4e0880-a1bb-11eb-96f2-c2cf636edd83.png">

<img width="1279" alt="Screen Shot 2021-04-20 at 9 33 11 AM" src="https://user-images.githubusercontent.com/3286252/115404761-a1c60e80-a1bb-11eb-9488-de692c4afab2.png">

**Comment by jberhang** [comment]
I am also seeing the same behavior in my app.

**Comment by DanC5** [comment]
@jberhang I just tested this on my end and refreshed the app 50 times and only had the network error show up one time, but even then it didn't affect the functionality of the app. Are you seeing your app impaired by this network error?

You might have requests timing out on your side due to connection issues, so you can always increase the timeout duration and see if that fixes it, https://getstream.io/chat/docs/javascript/init_and_users/?language=javascript

**Comment by jberhang** [comment]
I will try the timeout but yes the chat window fails to load completely.

<img width="969" alt="Screen Shot 2021-04-20 at 9 58 10 AM" src="https://user-images.githubusercontent.com/3286252/115408550-f3bc6380-a1be-11eb-89ab-6cb064d1521d.png">

**Comment by DanC5** [comment]
Hopefully that helps. Also, I'm not super familiar with Safari debugging, but if the issue persists with the increased timeout, it would be helpful if you could send the network response error the same way you might in Chrome.
