### ISSUE TITLE
jump to pinned/searched message

### ISSUE THREAD

**Issue by s4admin** [GetStream/stream-chat-react#872]
Trying to add slack style team chat to our application and evaluating GetStream.

When clicking on a pinned/search message I need to jump to that place in the chat history that contains the message... otherwise you have no context for the search result.  

Is this possible?  I can't find a way to do it with the MessageList component.

**Comment by DanC5** [comment]
Hello @s4admin, this is actually something we've discussed at length in the past. This feature becomes problematic when you have an old message and the only way to get to it is to paginate through a very long list. This process of consistently calling a load more function client-side leads to clunky UI. The coordinated effort necessary to sync up the backend and frontend teams to make this happen is significant, so for this reason it's not currently on our product roadmap.

Sorry if this isn't the answer you're looking for, and we might prioritize this feature in the second half of the year, but at the moment it's not on our radar. I'm going to close the issue since there's no active work here, thanks.

**Comment by wildebeast** [comment]
Adding another vote - we're also looking to implement this feature for our application.

**Comment by DanC5** [comment]
@wildebeast thanks for letting us know. I'll run this by our product team once again to get it on their radar.

**Comment by wildebeast** [comment]
Noticed it's possible w/ Sendbird fwiw: https://sendbird.com/docs/chat/v3/javascript/guides/group-channel#2-load-messages-by-timestamp-or-message-id

**Comment by chiragkumar-kiwi** [comment]
Hi @DanC5, We are also looking to implement this feature in our application.
