### ISSUE TITLE
Channel Name not Showing on Channel List

### ISSUE THREAD

**Issue by mobeendev** [GetStream/stream-chat-react#911]
for groups, the channel name is now showing & it is only showing the latest message as the title

![image](https://user-images.githubusercontent.com/10846423/117777863-b3905400-b245-11eb-98f6-4a35faf67263.png)

Also, tell me how to make the Channel Header dynamic.

 Here is the code:
 
```
import React, { useEffect, useState } from "react";
import { StreamChat } from "stream-chat";
import {
  Chat,
  Channel,
  ChannelHeader,
  ChannelList,
  LoadingIndicator,
  MessageInput,
  MessageList,
  Thread,
  Window,
} from "stream-chat-react";

import "stream-chat-react/dist/css/index.css";

const userToken= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9dQnlMpVvqKa8IQsZF_kfJhoQqSmuqsy-eE";

const filters = { type: "messaging", members: { $in: ["abdul"] } };
const sort = { last_message_at: -1 };

const App = () => {
  const [chatClient, setChatClient] = useState(null);

  useEffect(() => {
    const initChat = async () => {
      const client = StreamChat.getInstance("fyvv3z977283");

      await client.connectUser(
        {
          id: "abdul",
          name: "abdul",
        },
        userToken
      );
      setChatClient(client);
    };

    initChat();
  }, []);

  if (!chatClient) {
    return <LoadingIndicator />;
  }

  return (
    <Chat client={chatClient} theme="messaging dark">
      <ChannelList filters={filters} sort={sort} />
      <Channel>
        <Window>
          <ChannelHeader
            title={"Best Team in Gym"}
            image="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCBwRez42QTfH_Zyj46M1RkK4U57VVYSZlpQ&usqp=CAU"
          />
          <MessageList />
          <MessageInput />
        </Window>
        <Thread />
      </Channel>
    </Chat>
  );
};

export default App;
```
Thanks

**Comment by mobeendev** [comment]
I found it, I was missing the name and image param:

```
  const channel = serverClient.channel("messaging", 'my-group', {
      members: [u1, u2 , u3, u4],
      name:'group name',
      image:imageUrl
    });
```

Now just want to know about this:
 
How to make the Channel Header dynamic?

Right now I have this code :

```
 return (
    <Chat client={chatClient} theme="messaging dark">
      <ChannelList filters={filters} sort={sort} />
      <Channel>
        <Window>
          <ChannelHeader
            title={"Best Team in Gym"}
            image={url}
          />
          <MessageList />
          <MessageInput />
        </Window>
        <Thread />
      </Channel>
    </Chat>
  );
```

**Comment by mobeendev** [comment]
@DanC5 yes how I can receive the props from another component and use them here.

Also how I can customize the header to put any link so that I can go back to the main application.

**Comment by DanC5** [comment]
@mobeendev the ChannelHeader consumes from the ChatContext and ChannelContext providers, so you can use our custom hooks (useChatContext or useChannelContext) to pull any values that are stored in either one. (https://github.com/GetStream/stream-chat-react/tree/master/src/context)

If you'd like to customize the functionality of the ChannelHeader you're going to need to build your own component and put it in it's place. The ChannelHeader component is very simple (https://github.com/GetStream/stream-chat-react/blob/master/src/components/ChannelHeader/ChannelHeader.tsx), so you can always copy the logic from this file and add your own pieces to the code. Most of our clients build their own header, so this header isn't very extendable and customizable because of the simplicity in building your own. It's more of a guide showing you one option for a header component.

I hope this answers your questions but let me know, thanks!

**Comment by mobeendev** [comment]
@DanC5 can you give me a working example of this e.g sample code.

**Comment by DanC5** [comment]
@mobeendev it would look like the below, where you can pull any value out of our contexts with our custom context hooks...

```
const CustomHeader = () => {
  const channelContext = useChannelContext();
  const chatContext = useChatContext();

  return <div>Header Component</div>;
};

return (
  <Chat client={chatClient} theme='messaging dark'>
    <ChannelList filters={filters} sort={sort} />
    <Channel>
      <Window>
        <CustomHeader />
        <MessageList />
        <MessageInput />
      </Window>
      <Thread />
    </Channel>
  </Chat>
);
```

**Comment by mobeendev** [comment]
Thanks @DanC5.
