### ISSUE TITLE
Warning messages about the usage of UNSAFE_componentWillReceiveProps

### ISSUE THREAD

**Issue by anonimitoraf** [GetStream/stream-chat-react#941]
Specifically:
```
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: ReactTextareaAutocomplete
```

To give some context, the reason why I'm interested in this message is because:
* I'm using Clojurescript + stream-chat-react
* I get the following error message when pressing `Enter` to send a message:
```
Uncaught TypeError: _this.textareaRef.matches is not a function
    at ReactTextareaAutocomplete.eval [as _onEnter] (index.cjs.js:1231)
    at eval (index.cjs.js:1703)
    at eval (index.cjs.js:941)
    at Array.forEach (<anonymous>)
    at HTMLDocument.Listener.f (index.cjs.js:930)
```
It points to this code (Clojurescript compiled so it look different):
`var hasFocus = _this.textareaRef.matches(':focus'); // Don't submit if the element doesn't have focus or the shift key is pressed, unless shift+Enter were provided as submit keys`

I've got a feeling the UNSAFE_componentWillReceiveProps warning message is related to this error message.

---

I know it's not fair to ask for a fix for this, since the components work in JS so, I simply wanted to ask whether you guys have an idea why that warning message exists.
I'm happy to make a PR for a fix but I don't (currently) understand most of the code. Happy to be guided if possible.

Thanks

**Comment by anonimitoraf** [comment]
Alternatively, are there docs for how to create a custom `AutoComplete` component? Or how to plugin a simple input component into `MessageInput`? (Say I'm not interested in having an `AutoComplete` component

**Comment by DanC5** [comment]
Hello @anonimitoraf, as the sample apps we test on are in TypeScript, I'm familiar with this warning. TypeScript doesn't like that the logic in this component is using a deprecated React lifecycle method, also since the JS isn't properly type checked, this error is popping up for you. However, it is in our Q3 roadmap to replace the `AutoCompleteTextarea` component with an updated, rich text input that's fully up to date and in TypeScript. So hopefully but late summer/early fall we'll be able to roll out the updated textarea component.

If you need to replace this component now, you will have to create your own version of our `ChatAutoComplete` component, which wraps `AutoCompleteTextarea` and passes in a bunch of our context values via props, https://github.com/GetStream/stream-chat-react/blob/master/src/components/ChatAutoComplete/ChatAutoComplete.tsx#L197.

The `AutoCompleteTextarea` component handles a ton of logic so unless replacement is critical, I'd recommend living with the warnings for now. Not only would replacing this component be a pretty heavy lift, but the logic works pretty well (hence why we haven't updated the code yet), so the chances of creating bugs for yourself trying to mirror the functionality is high.

If you're going to stick with this component for now, you can subscribe to release notifications on the library. And if you're going to replace, feel free to reach out if other questions arise in the process. I'm going to close the issue as there isn't any further action for me to take, thanks!
