### ISSUE TITLE
userToken does not have a user_id or is not matching with user.id

### ISSUE THREAD

**Issue by mobeendev** [GetStream/stream-chat-react#956]
Here is the code which I am using to initialize user, and adding it to the channel:

```
useEffect(async () => {
    const initChat = async () => {
      const _queryString = window.location.search;

      let data = queryString.parse(_queryString);
 
      let reg_url = 'our.backend.url';                     //to create user token
      const result = await axios(reg_url);
      console.log(result.data.user);
      
      if (result.data) { 
          
            setUserName(result.data.user.username);     
            setUserToken(result.data.user.userToken);
            setUserId(result.data.user.userid);
            setAppToken(data.apptoken);
            
            if (userId && userName && userToken) { 
                  const client = StreamChat.getInstance(API_KEY);
                  setChatClient(client);
                  await client.connectUser({ id: userId, name: userName }, userToken);
                  const channel = client.channel("messaging", "oxapp", {});
                  await channel.addMembers([userId]);
            }
      }

    };

    initChat();

    return () => {
      chatClient.disconnectUser();
    };
  }, [userToken,chatClient, userId , userName ]);
```

**Comment by DanC5** [comment]
@mobeendev it appears the `userId` and `userToken` you're passing into your `connectUser` call do not match. This leads me to believe something isn't set up properly where you are [creating the token server-side](https://getstream.io/chat/docs/javascript/tokens_and_authentication/#generating-tokens). You can verify the ID and token match with the [JWT generator on our website](https://getstream.io/chat/docs/javascript/token_generator/). Do you mind sharing your server-side token generation code?

I'm going to close this issue just because this forum is meant to address bugs/improvements with the library, but I'll still continue to receive notifications and reply on here. But just for future reference, support@getstream.io is where you'll want to send these kinds of inquiries, thanks.
