### ISSUE TITLE
Setting Limit for Mentions Search Autocomplete

### ISSUE THREAD

**Issue by forgingdestiny** [GetStream/stream-chat-react#987]
For MessageInput when using mentions autocomplete...

Using mentionQueryParams on the MessageInput only takes effect when mentionAllAppUsers is on.  It would be nice to be able to customize/increase the limit when the default is used and getMembersAndWatchers() is used in [the component](https://github.com/GetStream/stream-chat-react/blob/0741ce3cf2d7200e08c57bc45524eaf4c78b809e/src/components/MessageInput/hooks/useUserTrigger.ts#L160).

The data is hard-coded to 10, so if someone is typing in a channel more than 10 users that match, it's limiting and requires more customization to set mentionAllAppUsers (which we don't want to do in this case) and re-create the query to get only channel members.

https://github.com/GetStream/stream-chat-react/blob/0741ce3cf2d7200e08c57bc45524eaf4c78b809e/src/components/MessageInput/hooks/useUserTrigger.ts#L160

**Comment by DanC5** [comment]
@forgingdestiny good point and very reasonable request, going to look into supporting this right now. I'll get back to you soon.

**Comment by DanC5** [comment]
@forgingdestiny just made a simple library addition to handle this request. You can now pass a limit to the `mentionQueryParams` prop and have it reflected in the slice. It'll look like this...

```
<MessageInput mentionQueryParams={{ options: { limit: 15 } }} />
```

Here's the PR, https://github.com/GetStream/stream-chat-react/pull/988. There's a chance we'll make a release before EOD, but otherwise it'll go live Monday as we're off work tomorrow.

Thanks!

**Comment by forgingdestiny** [comment]
Wow! Awesome. Thanks for the fast reply and addition. 🙏
