### ISSUE TITLE
Cannot find asset

### ISSUE THREAD

**Issue by zperlo** [GetStream/stream-chat-react#998]
I just upgraded to the newest version, and I'm getting an error when running it: `Error: Cannot find module '../../assets/Poweredby_100px-White_VertText.png'` that seems to originate from this package. Is this a bug? Can this be fixed?

**Comment by DanC5** [comment]
@zperlo are you using a Next.js app? If so you need to add `next-images` to your config file. We recently had to do something similar for our example app built in Next. See this PR for instructions, https://github.com/GetStream/stream-chat-react/pull/920/files

**Comment by zperlo** [comment]
@DanC5 I'm using a Meteor app.

**Comment by DanC5** [comment]
Ok, I have not used Meteor but I would imagine you need to do something similar for that platform.

**Comment by DanC5** [comment]
@zperlo this might set you on the right path, https://forums.meteor.com/t/static-assets-compiler-released-import-images-etc-into-your-js-files/41781

**Comment by zperlo** [comment]
Hmm, that didn't work for me.

**Comment by DanC5** [comment]
@zperlo I'm assuming this issue is arising for you as part of our restructure around the bundle building process. We put some tree shaking enhancements in place in v5.4.0, https://github.com/GetStream/stream-chat-react/releases/tag/v5.4.0. I'm guessing that your Meteor app is attempting to load our module bundle without the proper setup to support this, and therefore throwing this error (which was similar to the Next.js issue referenced earlier and fixed with the `next-images` dependency).

Full disclosure I haven't used Meteor and you probably also want to reach out on their forums, but you likely need to either get your app to point towards the common JS bundle (and not the module one) or figure our how to properly load the module bundle in your app.

If you see in our `package.json` file, the main entry point is common JS and the module structure has been preserved for the module entry point, https://github.com/GetStream/stream-chat-react/blob/master/package.json#L8-L9.

**Comment by zperlo** [comment]
I'm currently checking with people who know meteor better than I do. @DanC5 If I can't figure out a way to get that working, what is the latest version that doesn't use these static assets?

**Comment by DanC5** [comment]
Hey @zperlo I'm pretty sure the issue for you is this line right here being a module import and not using require syntax, https://github.com/GetStream/stream-chat-react/blob/master/src/components/Attachment/Card.tsx#L5

Can you go into your node_modules and change the code to the following?

```
const giphyLogo = require('../../assets/Poweredby_100px-White_VertText.png');
```

If this fixes the issue for you, I think it might make sense to make this change globally.

**Comment by zperlo** [comment]
That did not work for me, unfortunately. I'll keep looking for fixes within meteor.

**Comment by DanC5** [comment]
Hey @zperlo one more thing to try would be to import the component library using require syntax, so like...

`const streamChatReact = require('stream-chat-react');`
